//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativeItem
    {
        public int Id { get; set; }
        public Nullable<int> MainItemId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
