//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.CashTransfers = new HashSet<CashTransfer>();
            this.CashTransfers1 = new HashSet<CashTransfer>();
            this.ChequeIssues = new HashSet<ChequeIssue>();
            this.ChequeReceipts = new HashSet<ChequeReceipt>();
            this.Departments = new HashSet<Department>();
            this.PurchaseInvoicePaymentMethods = new HashSet<PurchaseInvoicePaymentMethod>();
            this.PurchaseReturnPaymentMethods = new HashSet<PurchaseReturnPaymentMethod>();
            this.SalesInvoicePaymentMethods = new HashSet<SalesInvoicePaymentMethod>();
            this.UpdatedTransactionPaymentMethods = new HashSet<UpdatedTransactionPaymentMethod>();
            this.SalesOrderPaymentMethods = new HashSet<SalesOrderPaymentMethod>();
            this.CashReceiptVouchers = new HashSet<CashReceiptVoucher>();
            this.CashIssueVouchers = new HashSet<CashIssueVoucher>();
            this.ServiceInvoicePaymentMethods = new HashSet<ServiceInvoicePaymentMethod>();
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Branch { get; set; }
        public Nullable<int> BankAccountPaymentId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> BankAccountReceiptId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual ChartOfAccount ChartOfAccount1 { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransfer> CashTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransfer> CashTransfers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeIssue> ChequeIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeReceipt> ChequeReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoicePaymentMethod> PurchaseInvoicePaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnPaymentMethod> PurchaseReturnPaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoicePaymentMethod> SalesInvoicePaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdatedTransactionPaymentMethod> UpdatedTransactionPaymentMethods { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderPaymentMethod> SalesOrderPaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashReceiptVoucher> CashReceiptVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashIssueVoucher> CashIssueVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInvoicePaymentMethod> ServiceInvoicePaymentMethods { get; set; }
    }
}
