//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarWorkOrder()
        {
            this.CarWorkOrderDetails = new HashSet<CarWorkOrderDetail>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string CarPlateNumber { get; set; }
        public string CarSerialNumber { get; set; }
        public Nullable<int> CarTypeId { get; set; }
        public Nullable<int> CarColorId { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public Nullable<int> CarServiceCategoryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalAfterTaxes { get; set; }
        public Nullable<decimal> VoucherDiscountValue { get; set; }
        public Nullable<double> VoucherDiscountPercentage { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> SalesTaxes { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<bool> AutoCreated { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public string CarInOdometer { get; set; }
        public string CarOutOdometer { get; set; }
    
        public virtual CarColor CarColor { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual CarServiceCategory CarServiceCategory { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarWorkOrderDetail> CarWorkOrderDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
