//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransfer
    {
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> BankIdFrom { get; set; }
        public Nullable<int> BankAccountIdFrom { get; set; }
        public string BankBranchFrom { get; set; }
        public Nullable<int> BankIdTo { get; set; }
        public Nullable<int> BankAccountIdTo { get; set; }
        public string BankBranchTo { get; set; }
        public Nullable<int> CashBoxIdFrom { get; set; }
        public Nullable<int> CashBoxIdTo { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> TotalMoneyAmount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> TransferTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<int> DepartmentIdTo { get; set; }
        public Nullable<int> ChartOfAccountIdFrom { get; set; }
        public Nullable<int> ChartOfAccountIdTo { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Bank Bank1 { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual BankAccount BankAccount1 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual CashBox CashBox1 { get; set; }
        public virtual CashTransferType CashTransferType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual SystemPage SystemPage { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual ChartOfAccount ChartOfAccount1 { get; set; }
    }
}
