//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashIssueVoucherEmployeePayrollIssue
    {
        public int Id { get; set; }
        public Nullable<int> CashIssueVoucherId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
    
        public virtual CashIssueVoucher CashIssueVoucher { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
