//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurchMembership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChurchMembership()
        {
            this.ChurchMembershipVisits = new HashSet<ChurchMembershipVisit>();
            this.ChurchMeetings = new HashSet<ChurchMeeting>();
            this.ChurchMembership1 = new HashSet<ChurchMembership>();
            this.MemberSpiritualNotes = new HashSet<MemberSpiritualNote>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string ConfessionFather { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsAlive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Image { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Relative { get; set; }
        public string TopicsForDiscussion { get; set; }
        public Nullable<bool> IsUseApplication { get; set; }
        public string Email { get; set; }
        public string PlayerId { get; set; }
        public string Password { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> ChurchFatherId { get; set; }
        public Nullable<bool> FollowUp { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChurchMembershipVisit> ChurchMembershipVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChurchMeeting> ChurchMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChurchMembership> ChurchMembership1 { get; set; }
        public virtual ChurchMembership ChurchMembership2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSpiritualNote> MemberSpiritualNotes { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ChurchFather ChurchFather { get; set; }
    }
}
