//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurchMeeting
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> ChurchMembershipId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ConfessionFather { get; set; }
        public string Mobile { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Image { get; set; }
        public Nullable<int> ChurchFatherId { get; set; }
    
        public virtual ChurchMembership ChurchMembership { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual ChurchFather ChurchFather { get; set; }
    }
}
