//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionSetting
    {
        public int Id { get; set; }
        public Nullable<decimal> MoneyAmountFrom { get; set; }
        public Nullable<decimal> MoneyAmountTo { get; set; }
        public Nullable<double> CommissionPercentage { get; set; }
        public Nullable<double> CommissionFifteenDays { get; set; }
        public Nullable<double> CommissionMonth { get; set; }
        public Nullable<double> CommissionTwoMonths { get; set; }
        public Nullable<double> CommissionThreeMonths { get; set; }
        public Nullable<double> CommissionMoreThanThreeMonths { get; set; }
    }
}
