//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionResult
    {
        public int Id { get; set; }
        public Nullable<int> CompetitorId { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> NoOfCorrectAnswers { get; set; }
    
        public virtual Competitor Competitor { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
