//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorQuestionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitorQuestionDetail()
        {
            this.CompetitorAnswers = new HashSet<CompetitorAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompetitorQuestionId { get; set; }
        public string Question { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitorAnswer> CompetitorAnswers { get; set; }
        public virtual CompetitorQuestion CompetitorQuestion { get; set; }
    }
}
