//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCoupon
    {
        public int Id { get; set; }
        public int CouponId { get; set; }
        public int CustomerId { get; set; }
        public int OrderID { get; set; }
        public decimal DiscountAmount { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Order Order { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesOrder SalesOrder1 { get; set; }
    }
}
