//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayUseReservation
    {
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PeopleNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAfterDiscount { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CashBoxId { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Remain { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual Department Department { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
