//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBChange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBChange()
        {
            this.SyncedDepartments = new HashSet<SyncedDepartment>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public bool IsMasterChange { get; set; }
        public bool IsNew { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public bool IsTransaction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncedDepartment> SyncedDepartments { get; set; }
    }
}
