//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalSubjectDetail
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public string LectureName { get; set; }
        public string LecturerName { get; set; }
        public string VideoLink { get; set; }
        public string PDFLink { get; set; }
        public string PowerPointLink { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
    
        public virtual EducationalSubject EducationalSubject { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
