//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMonthlyAllocationDetail
    {
        public int Id { get; set; }
        public int MainDocId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeMonthlyAllocation EmployeeMonthlyAllocation { get; set; }
    }
}
