//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesAttendAndLeaveDetail
    {
        public int Id { get; set; }
        public string EmpCodeOnFingerPrint { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeArName { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EmployeesAttendAndLeaveId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> In_Out { get; set; }
        public Nullable<System.DateTime> Attend_LeaveDateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeesAttendAndLeave EmployeesAttendAndLeave { get; set; }
    }
}
