//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFollowUp
    {
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> FollowUpTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> VacationStartDate { get; set; }
        public Nullable<System.DateTime> VacationEndDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
