//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMonthlyAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeMonthlyAllocation()
        {
            this.EmployeeMonthlyAllocationDetails = new HashSet<EmployeeMonthlyAllocationDetail>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> AllocationTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
    
        public virtual AllocationType AllocationType { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeMonthlyAllocationDetail> EmployeeMonthlyAllocationDetails { get; set; }
    }
}
