//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPreviousVacationDetail
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> VacationStartDate { get; set; }
        public Nullable<System.DateTime> VacationEndDate { get; set; }
        public Nullable<System.DateTime> VacationActualReturnDate { get; set; }
        public Nullable<int> AllowedDaysNumber { get; set; }
        public Nullable<int> ActualDaysNumber { get; set; }
        public Nullable<int> LateDaysNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmpPreviousVacation EmpPreviousVacation { get; set; }
    }
}
