//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    
    public partial class FinancialPeriods_GetPreviousPeriod_Result1
    {
        public int Id { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<bool> PostingStatus { get; set; }
        public Nullable<bool> LockStatus { get; set; }
        public Nullable<bool> Opened { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Status { get; set; }
    }
}
