//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAssetScrapingDetail
    {
        public int Id { get; set; }
        public int FixedAssetId { get; set; }
        public int MainDocId { get; set; }
        public decimal FixedAssetValue { get; set; }
        public decimal CurrentFixedAssetValue { get; set; }
        public decimal HistoricalValueOfAsset { get; set; }
        public Nullable<System.DateTime> LastDepreciationDate { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual FixedAsset FixedAsset { get; set; }
        public virtual FixedAssetScraping FixedAssetScraping { get; set; }
    }
}
