//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedAsset()
        {
            this.FixedAssetDepreciationDetails = new HashSet<FixedAssetDepreciationDetail>();
            this.FixedAssetScrapingDetails = new HashSet<FixedAssetScrapingDetail>();
            this.FixedAssetSellingDetails = new HashSet<FixedAssetSellingDetail>();
            this.Employees = new HashSet<Employee>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.Properties = new HashSet<Property>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> FixedAssetsGroupId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> ValueOfAsset { get; set; }
        public Nullable<decimal> HistoricalValueOfAsset { get; set; }
        public Nullable<double> NumberOfYears { get; set; }
        public int ChartOfAccountsIdTotalDepracition { get; set; }
        public int ChartOfAccountsIdOriginalAccounts { get; set; }
        public int ChartOfAccountsIdDepracition { get; set; }
        public Nullable<int> CapitalGainsAccounts { get; set; }
        public Nullable<int> CapitalLossesAccounts { get; set; }
        public Nullable<System.DateTime> StartDepraciationDate { get; set; }
        public Nullable<decimal> TotalDepracaition { get; set; }
        public Nullable<int> DepreciationMethod { get; set; }
        public Nullable<double> ValueOfInstallment { get; set; }
        public Nullable<double> DepraciationRate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> FixedAssetStatusId { get; set; }
        public Nullable<int> FixedAssetTypeId { get; set; }
        public Nullable<bool> IsHasNoDepreciation { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<int> FieldsCodingId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Department Department { get; set; }
        public virtual FixedAssetsGroup FixedAssetsGroup { get; set; }
        public virtual FixedAssetStatu FixedAssetStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedAssetDepreciationDetail> FixedAssetDepreciationDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedAssetScrapingDetail> FixedAssetScrapingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedAssetSellingDetail> FixedAssetSellingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual FixedAssetsType FixedAssetsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual FieldsCoding FieldsCoding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
    }
}
