//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    
    public partial class GetBuildingRooms_Panel_Result1
    {
        public int RoomBookingId { get; set; }
        public int RoomId { get; set; }
        public Nullable<System.DateTime> BookingStartDate { get; set; }
        public Nullable<System.DateTime> BookingEndDate { get; set; }
        public Nullable<bool> RoomBookingIsReserved { get; set; }
        public Nullable<int> BookingStatusId { get; set; }
        public string BookingStatusName { get; set; }
        public string RoomCode { get; set; }
        public Nullable<int> RoomStatusId { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string FloorName { get; set; }
        public int BuildingId { get; set; }
        public string BuildingArName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
    }
}
