//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    
    public partial class GetUnSelectedExpenseAmortization_Result1
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public string ArName { get; set; }
        public Nullable<bool> IsSelectedAmortization { get; set; }
        public Nullable<int> ExpenseAmortizationId { get; set; }
        public Nullable<bool> IsSelectedProof { get; set; }
        public Nullable<int> ExpenseProofId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Department { get; set; }
        public decimal Value { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<int> ExpenseTypeId { get; set; }
        public string ExpenseAccount { get; set; }
        public Nullable<int> ExpenseAccountId { get; set; }
        public string PrePaymentAccount { get; set; }
        public Nullable<int> PrePaymentAccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public string CostCenterCode { get; set; }
        public string CostCenterName { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
    }
}
