//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueAnalysisDetail
    {
        public int Id { get; set; }
        public int PropertyDetailId { get; set; }
        public decimal Price { get; set; }
        public int IssueAnalysisId { get; set; }
    
        public virtual IssueAnalysis IssueAnalysi { get; set; }
        public virtual PropertyDetail PropertyDetail { get; set; }
    }
}
