//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVendor
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Image { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual Item Item { get; set; }
    }
}
