//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemComponent
    {
        public int Id { get; set; }
        public int ParentItemId { get; set; }
        public int ChildItemId { get; set; }
        public double Quantity { get; set; }
        public int ItemUnitId { get; set; }
        public double UnitEquivalent { get; set; }
        public double ToleranceQty { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
    
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual Item Item { get; set; }
    }
}
