//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInsertion
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public string KrName { get; set; }
        public Nullable<int> OrderLimit { get; set; }
        public Nullable<int> ItemGroupId { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public Nullable<bool> HasWarranty { get; set; }
        public Nullable<bool> HasExpiry { get; set; }
        public Nullable<int> WarrantyDays { get; set; }
        public Nullable<int> WarrantyMonths { get; set; }
        public Nullable<int> WarrantyYears { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string ArNotes { get; set; }
        public string KrNotes { get; set; }
        public string Image { get; set; }
        public string IdOnWebSite { get; set; }
        public string ProductNo { get; set; }
        public Nullable<double> VirtualQuantity { get; set; }
        public string EnDetails { get; set; }
        public string ArDetails { get; set; }
        public string KrDetails { get; set; }
        public Nullable<bool> IsAccessory { get; set; }
        public Nullable<bool> HasAccessory { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> FieldsCodingId { get; set; }
        public Nullable<bool> NotIncludeValueAddedTax { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public string Barcode1 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<int> ItemUnitId1 { get; set; }
        public Nullable<int> Equivalent1 { get; set; }
        public Nullable<int> CustomerGroupId1 { get; set; }
        public string Barcode2 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<int> ItemUnitId2 { get; set; }
        public Nullable<int> Equivalent2 { get; set; }
        public Nullable<int> CustomerGroupId2 { get; set; }
        public string Barcode3 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<int> ItemUnitId3 { get; set; }
        public Nullable<int> Equivalent3 { get; set; }
        public Nullable<int> CustomerGroupId3 { get; set; }
    }
}
