//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCostPrice
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> QtyBefore { get; set; }
        public Nullable<double> QtyAfter { get; set; }
        public Nullable<decimal> CostBefore { get; set; }
        public decimal CostAfter { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> AutoCreated { get; set; }
        public string Notes { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Item Item { get; set; }
    }
}
