//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JournalEntry()
        {
            this.JournalEntryDetails = new HashSet<JournalEntryDetail>();
            this.PropertyContractBatches = new HashSet<PropertyContractBatch>();
            this.PropertyContracts = new HashSet<PropertyContract>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public System.DateTime Date { get; set; }
        public string DateHijri { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SourcePageId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public bool IsDeleted { get; set; }
        public string Image { get; set; }
        public Nullable<int> UserId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> Equivalent { get; set; }
        public string OriginalDocumentNumber { get; set; }
        public Nullable<int> OriginalNoteId { get; set; }
        public Nullable<int> OriginalNoteType { get; set; }
        public string OriginalSerial { get; set; }
        public string MigrationSource { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalEntryDetail> JournalEntryDetails { get; set; }
        public virtual SystemPage SystemPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContractBatch> PropertyContractBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContract> PropertyContracts { get; set; }
    }
}
