//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturingOrder
    {
        public int Id { get; set; }
        public int ManufacturingRequestId { get; set; }
        public int WarehouseId { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> AutoCreated { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public int ChefId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> AcceptanceDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ManufacturingRequest ManufacturingRequest { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
