//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OvertimeIssue()
        {
            this.AttendAndLeaveApprovalDetails = new HashSet<AttendAndLeaveApprovalDetail>();
            this.OvertimeIssueDetials = new HashSet<OvertimeIssueDetial>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int EmployeeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendAndLeaveApprovalDetail> AttendAndLeaveApprovalDetails { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeIssueDetial> OvertimeIssueDetials { get; set; }
    }
}
