//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyIssueDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PenaltyIssueDetail()
        {
            this.AttendAndLeaveApprovalDetails = new HashSet<AttendAndLeaveApprovalDetail>();
        }
    
        public int Id { get; set; }
        public int MainDocId { get; set; }
        public System.DateTime Date { get; set; }
        public int PenaltyTypeId { get; set; }
        public double Equivalent { get; set; }
        public string Cause { get; set; }
        public decimal Total { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PenaltyType PenaltyType { get; set; }
        public virtual PenaltyIssue PenaltyIssue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendAndLeaveApprovalDetail> AttendAndLeaveApprovalDetails { get; set; }
    }
}
