//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosClosingCurrencyCategory
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public Nullable<double> CurrencyCategory { get; set; }
        public Nullable<decimal> Count { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public string Notes { get; set; }
    
        public virtual PosClosing PosClosing { get; set; }
    }
}
