//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosReceiptVoucherCustomerType
    {
        public int Id { get; set; }
        public Nullable<int> PosReceiptVoucherId { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual PosReceiptVoucher PosReceiptVoucher { get; set; }
    }
}
