//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyContractTermination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyContractTermination()
        {
            this.PropertyContractTerminationDamages = new HashSet<PropertyContractTerminationDamage>();
            this.PropertyContractTerminationDetails = new HashSet<PropertyContractTerminationDetail>();
            this.CashReceiptVoucher = new HashSet<CashReceiptVoucher>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public Nullable<int> PropertyContractId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> PropertyUnitTypeId { get; set; }
        public Nullable<int> PropertyRenterId { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<System.DateTime> LastBatchDate { get; set; }
        public Nullable<bool> IsLastBatchCalculation { get; set; }
        public Nullable<bool> IsDocumented { get; set; }
        public Nullable<decimal> IncreaseDayValue { get; set; }
        public Nullable<int> IncreaseDaysNo { get; set; }
        public Nullable<decimal> IncreaseDaysTotalValue { get; set; }
        public Nullable<decimal> DecreaseDayValue { get; set; }
        public Nullable<int> DecreaseDaysNo { get; set; }
        public Nullable<decimal> DecreaseDaysTotalValue { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> TotalUnpaidAmount { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<int> CalculationMethod { get; set; }
        public Nullable<decimal> RenterBalance { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual Property Property { get; set; }
        public virtual PropertyContract PropertyContract { get; set; }
        public virtual PropertyRenter PropertyRenter { get; set; }
        public virtual PropertyUnitType PropertyUnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContractTerminationDamage> PropertyContractTerminationDamages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContractTerminationDetail> PropertyContractTerminationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashReceiptVoucher> CashReceiptVoucher { get; set; }
    }
}
