//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyNotification
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string ContractNo { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> PropertyUnitTypeId { get; set; }
        public Nullable<int> PropertyOwnerId { get; set; }
        public Nullable<int> PropertyRenterId { get; set; }
        public string PropertyRenterMobile { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual PropertyOwner PropertyOwner { get; set; }
        public virtual PropertyRenter PropertyRenter { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual PropertyUnitType PropertyUnitType { get; set; }
    }
}
