//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyBillRegisteration
    {
        public int Id { get; set; }
        public int TransactionNumber { get; set; }
        public Nullable<System.DateTime> BillRegDate { get; set; }
        public int ContractId { get; set; }
        public int RenterId { get; set; }
        public int PropertyDetailId { get; set; }
        public Nullable<decimal> GasBillValue { get; set; }
        public Nullable<decimal> ElectricityBillValue { get; set; }
        public Nullable<decimal> ViolationBillValue { get; set; }
    
        public virtual PropertyContract PropertyContract { get; set; }
    }
}
