//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoicePaymentMethod
    {
        public int Id { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public int PurchaseInvoiceId { get; set; }
        public int PaymentMethodId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CashBoxId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
