//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePrivilege
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<bool> Privileged { get; set; }
    
        public virtual ERPRole ERPRole { get; set; }
        public virtual PageAction PageAction { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
