//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBookingDay
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<int> RoomBookingId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual RoomBooking RoomBooking { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
