//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesOrdersSalesInvoices = new HashSet<SalesOrdersSalesInvoice>();
            this.SalesOrderPaymentMethods = new HashSet<SalesOrderPaymentMethod>();
            this.CustomerCoupons = new HashSet<CustomerCoupon>();
            this.CustomerCoupons1 = new HashSet<CustomerCoupon>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public int WarehouseId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public Nullable<int> VendorOrCustomerId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalItemsDiscount { get; set; }
        public Nullable<decimal> SalesTaxes { get; set; }
        public Nullable<decimal> TotalAfterTaxes { get; set; }
        public Nullable<decimal> VoucherDiscountValue { get; set; }
        public Nullable<double> VoucherDiscountPercentage { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<int> DestinationWarehouseId { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<decimal> TotalCostPrice { get; set; }
        public Nullable<decimal> TotalItemDirectExpenses { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> AutoCreated { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public string DeliveredTo { get; set; }
        public Nullable<decimal> CommercialRevenueTaxAmount { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> ServiceFees { get; set; }
        public int CustomerType { get; set; }
        public Nullable<int> PosId { get; set; }
        public Nullable<int> CashierUserId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<bool> IsCollected { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<int> ReservationMethodId { get; set; }
        public Nullable<int> AdministrativeDepartmentId { get; set; }
        public Nullable<int> CustomerAddressId { get; set; }
        public Nullable<int> SatusId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> CustomerRepId { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<decimal> RefundableInsurance { get; set; }
        public Nullable<int> PosCustomerId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrdersSalesInvoice> SalesOrdersSalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderPaymentMethod> SalesOrderPaymentMethods { get; set; }
        public virtual ERPUser ERPUser1 { get; set; }
        public virtual Pos Pos { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual AdministrativeDepartment AdministrativeDepartment { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual SalesOrderStatu SalesOrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCoupon> CustomerCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCoupon> CustomerCoupons1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PosCustomer PosCustomer { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
