//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSetting
    {
        public int Id { get; set; }
        public Nullable<decimal> CompanyFees { get; set; }
        public Nullable<decimal> MinimumCharge { get; set; }
        public Nullable<decimal> PointValue { get; set; }
        public Nullable<double> AllowedDistance { get; set; }
        public Nullable<double> OrderFeesPercentage { get; set; }
    }
}
