//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceInvoice()
        {
            this.ServiceInvoiceDetails = new HashSet<ServiceInvoiceDetail>();
            this.ServiceInvoicePaymentMethods = new HashSet<ServiceInvoicePaymentMethod>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> SalesTaxes { get; set; }
        public Nullable<decimal> TotalAfterTaxes { get; set; }
        public Nullable<decimal> VoucherDiscountValue { get; set; }
        public Nullable<double> VoucherDiscountPercentage { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<decimal> TotalItemDirectExpenses { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> AutoCreated { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> CommercialRevenueTaxAmount { get; set; }
        public Nullable<int> CustomerRepId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual SystemPage SystemPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInvoiceDetail> ServiceInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInvoicePaymentMethod> ServiceInvoicePaymentMethods { get; set; }
    }
}
