//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInvoiceDetail
    {
        public int Id { get; set; }
        public int MainDocId { get; set; }
        public string ServiceName { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<double> DiscountPerc { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<double> ItemTaxPercentage { get; set; }
        public Nullable<decimal> ItemTaxValue { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual SystemPage SystemPage { get; set; }
        public virtual ServiceInvoice ServiceInvoice { get; set; }
    }
}
