//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialInsurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocialInsurance()
        {
            this.SocialInsuranceDetails = new HashSet<SocialInsuranceDetail>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EmployeeDepartmentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TotalCompanyPercentage { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialInsuranceDetail> SocialInsuranceDetails { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
