//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int Id { get; set; }
        public Nullable<bool> PrintTransactionsAfterAdd { get; set; }
        public Nullable<bool> PrintTransactionsAfterEdit { get; set; }
        public Nullable<bool> ShowDirectExpense { get; set; }
        public Nullable<bool> ShowSalesPrices { get; set; }
        public Nullable<bool> ShowSerialNumbers { get; set; }
        public Nullable<int> DefaultDepartmentId { get; set; }
        public Nullable<int> DefaultWarehouseId { get; set; }
        public Nullable<int> DefaultCashBoxId { get; set; }
        public Nullable<int> DefaultBankId { get; set; }
        public Nullable<bool> WarehouseItemsDistribution { get; set; }
        public Nullable<System.DateTime> MostSalesLastUpdate { get; set; }
        public Nullable<bool> PayViaCheque { get; set; }
        public Nullable<bool> PayViaVisa { get; set; }
        public Nullable<bool> PayViaCarryOver { get; set; }
        public Nullable<bool> PayViaCash { get; set; }
        public Nullable<double> ServiceFeesPercentage { get; set; }
        public double VisaCommissionPercentage { get; set; }
        public bool UseCostCenter { get; set; }
        public Nullable<bool> ApplyTaxesOnSalesIvoiceAuto { get; set; }
        public Nullable<bool> ShowDashBoard { get; set; }
        public int NoOfItemGroupsInPOS { get; set; }
        public int NoOfItemsInPOS { get; set; }
        public Nullable<bool> EnableAdditionalItemsOnPos { get; set; }
        public Nullable<double> DefaultQuantityInPos { get; set; }
        public Nullable<bool> AllowToAddSameItemMultipleTimes { get; set; }
        public Nullable<bool> ShowItemImageInsteadOfItemName { get; set; }
        public Nullable<double> WidthOfImage { get; set; }
        public Nullable<double> HeightOfImage { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> ShowCashBoxBalance { get; set; }
        public Nullable<bool> AllowSalesOrderInPos { get; set; }
        public Nullable<bool> IssueComponentsOfItemInStockIssue { get; set; }
        public Nullable<bool> UseMultiWarehousesInSalesInvoice { get; set; }
        public Nullable<bool> UseItemUnit { get; set; }
        public Nullable<bool> ShowUserTasks { get; set; }
        public Nullable<bool> ShowUserIcons { get; set; }
        public Nullable<bool> PrintReceiptInsteadOfSalesInvoice { get; set; }
        public Nullable<bool> PricingDependOnCustGroups { get; set; }
        public Nullable<bool> SendNotificationToWarehousesKeepers { get; set; }
        public Nullable<bool> AllowDiscountPerItemInSalesInvoice { get; set; }
        public Nullable<bool> UseExpiryDateForItems { get; set; }
        public Nullable<bool> UseAvgCostPrice { get; set; }
        public Nullable<bool> BarcodeUsingCameraInSalesInvoice { get; set; }
        public Nullable<bool> ShowSalesInvoiceProfit { get; set; }
        public string CommercialRegistrationNo { get; set; }
        public string TaxCardNumber { get; set; }
        public Nullable<int> DaysNo { get; set; }
        public Nullable<bool> ShowItemsInsteadOfItemGroupsInInventoryVoucher { get; set; }
        public Nullable<int> InvoiceSampleNo { get; set; }
        public Nullable<bool> UseRefundableInsurancesForAccessories { get; set; }
        public string CompanyArName { get; set; }
        public string CompanyEnName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string StreetArName { get; set; }
        public string StreetEnName { get; set; }
        public Nullable<bool> ShowDepartmentItemsInInventoryVoucher { get; set; }
        public Nullable<bool> PrintEInvoiceInsteadOfSalesInvoice { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<bool> IsFixedPart { get; set; }
        public string FixedPart { get; set; }
        public Nullable<bool> IsSeparator { get; set; }
        public string Separator { get; set; }
        public Nullable<int> NoOfDigits { get; set; }
        public Nullable<bool> DocumentCoding { get; set; }
        public Nullable<bool> UseSeparatedAccountsForWarehouse { get; set; }
        public Nullable<bool> WorkWithCommercialPOS { get; set; }
        public Nullable<bool> ShowExpireContracts { get; set; }
        public Nullable<int> ExpireContractsDays { get; set; }
        public Nullable<bool> ShowExpireResidencies { get; set; }
        public Nullable<int> ExpireResidenciesDays { get; set; }
        public Nullable<bool> ShowExpireLicenses { get; set; }
        public Nullable<int> ExpireLicensesDays { get; set; }
        public Nullable<bool> ShowExpirePassports { get; set; }
        public Nullable<int> ExpirePassportsDays { get; set; }
        public Nullable<bool> UseDifferentCurrencies { get; set; }
        public Nullable<bool> UseActivityLogo { get; set; }
        public Nullable<bool> ShowItemWidthAndHeightAndAreaInTransactions { get; set; }
        public Nullable<bool> UsePricePolicyIncludedInItemsValueAddedTax { get; set; }
        public Nullable<bool> AddItemBarcodeBasedOnItemCode { get; set; }
        public Nullable<bool> ApplySmokingTax { get; set; }
        public Nullable<double> SmokingTaxPercentage { get; set; }
        public Nullable<bool> DontShowEndProductInPurchaseInvoice { get; set; }
        public Nullable<double> CashierMaximumAllowedDiscountPercentage { get; set; }
        public Nullable<bool> ShowTaxPercentageAndValue { get; set; }
        public Nullable<bool> UseThermalPrinterToPrintInvoices { get; set; }
        public Nullable<bool> NotAutomaticallyApprovingCashIssueAndCashReceiptVouchers { get; set; }
        public Nullable<bool> UsePrintingAssistantProgram { get; set; }
        public Nullable<bool> EnterEmployeeCodeManually { get; set; }
        public Nullable<bool> EnterItemCodeManually { get; set; }
        public Nullable<bool> IsDeliveryPossibility { get; set; }
        public Nullable<bool> IsTableSellingPossibility { get; set; }
        public Nullable<bool> IsTakeAwaySellingPossibility { get; set; }
        public string ItemsBarcodePrinterName { get; set; }
        public Nullable<bool> UseOverDraftPolicy { get; set; }
        public Nullable<bool> AutomaticallyApprovingSalesQuotation { get; set; }
        public Nullable<bool> InabilityToEditSalesAndPurchaseInvoicesAndReturns { get; set; }
        public Nullable<bool> LinkSalesRepresentativesWithCustomers { get; set; }
        public Nullable<bool> WorkingWithTheEgyptianVacationSystem { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Department Department { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
