//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicianAttachedFile
    {
        public int Id { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public bool IsActivates { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
    
        public virtual Techanician Techanician { get; set; }
    }
}
