//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserNotification()
        {
            this.OccuredNotifications = new HashSet<OccuredNotification>();
        }
    
        public Nullable<bool> Notification { get; set; }
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> ActionId { get; set; }
    
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OccuredNotification> OccuredNotifications { get; set; }
        public virtual PageAction PageAction { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
