//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseOB()
        {
            this.WarehouseOBDetails = new HashSet<WarehouseOBDetail>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> MoneyTotal { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Department Department { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOBDetail> WarehouseOBDetails { get; set; }
    }
}
