// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ECconnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=eazycash;Persist Security Info=True;User ID=sa;Password=******; Connection Timeout=900`
//     Include Views:          `True`

using System;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using Dapper.Contrib.Extensions;
namespace EazyCash.Data
{
    /// <summary>
    /// A class which represents the AspNetRoles table.
    /// </summary>
	[Table("[AspNetRoles]")]
	[Serializable()]
	public partial class AspNetRole:Bindable
	{

 
	[ExplicitKey]
		public virtual string Id 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Name 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string NormalizedName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ConcurrencyStamp 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the AspNetRoleClaims table.
    /// </summary>
	[Table("[AspNetRoleClaims]")]
	[Serializable()]
	public partial class AspNetRoleClaim:Bindable
	{

 
    [Key]
	public virtual int Id 
	{
            get { return Get<int>(); }
            set { Set(value); }
    }
	public virtual string RoleId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ClaimType 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ClaimValue 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the AspNetUserClaims table.
    /// </summary>
	[Table("[AspNetUserClaims]")]
	[Serializable()]
	public partial class AspNetUserClaim:Bindable
	{

 
    [Key]
	public virtual int Id 
	{
            get { return Get<int>(); }
            set { Set(value); }
    }
	public virtual string UserId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ClaimType 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ClaimValue 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the AspNetUserLogins table.
    /// </summary>
	[Table("[AspNetUserLogins]")]
	[Serializable()]
	public partial class AspNetUserLogin:Bindable
	{

 
	[ExplicitKey]
		public virtual string LoginProvider 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	[ExplicitKey]
		public virtual string ProviderKey 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ProviderDisplayName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string UserId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the AspNetUserRoles table.
    /// </summary>
	[Table("[AspNetUserRoles]")]
	[Serializable()]
	public partial class AspNetUserRole:Bindable
	{

 
	[ExplicitKey]
		public virtual string UserId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	[ExplicitKey]
		public virtual string RoleId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the AspNetUserTokens table.
    /// </summary>
	[Table("[AspNetUserTokens]")]
	[Serializable()]
	public partial class AspNetUserToken:Bindable
	{

 
	[ExplicitKey]
		public virtual string UserId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	[ExplicitKey]
		public virtual string LoginProvider 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	[ExplicitKey]
		public virtual string Name 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Value 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the AspNetUsers table.
    /// </summary>
	[Table("[AspNetUsers]")]
	[Serializable()]
	public partial class AspNetUser:Bindable
	{

 
	[ExplicitKey]
		public virtual string Id 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string UserName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string NormalizedUserName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Email 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string NormalizedEmail 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual bool EmailConfirmed 
	{
            get { return Get<bool>(); }
            set { Set(value); }
    }
	public virtual string PasswordHash 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string SecurityStamp 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string ConcurrencyStamp 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string PhoneNumber 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual bool PhoneNumberConfirmed 
	{
            get { return Get<bool>(); }
            set { Set(value); }
    }
	public virtual bool TwoFactorEnabled 
	{
            get { return Get<bool>(); }
            set { Set(value); }
    }
	public virtual string LockoutEnd 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual bool LockoutEnabled 
	{
            get { return Get<bool>(); }
            set { Set(value); }
    }
	public virtual int AccessFailedCount 
	{
            get { return Get<int>(); }
            set { Set(value); }
    }
	public virtual string BranchId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual bool IsAdmin 
	{
            get { return Get<bool>(); }
            set { Set(value); }
    }
	public virtual bool IsActive 
	{
            get { return Get<bool>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the ClientData table.
    /// </summary>
	[Table("[ClientData]")]
	[Serializable()]
	public partial class ClientData:Bindable
	{

 
    [Key]
	public virtual int Id 
	{
            get { return Get<int>(); }
            set { Set(value); }
    }
	public virtual DateTime? OrderDate 
	{
            get { return Get<DateTime?>(); }
            set { Set(value); }
    }
	public virtual string ArabicName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string EnglishName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string NationalId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual int? Resualt 
	{
            get { return Get<int?>(); }
            set { Set(value); }
    }
	public virtual int? ViolationCount 
	{
            get { return Get<int?>(); }
            set { Set(value); }
    }
	public virtual string Notes 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string DetecId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Description 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string UserId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string BranchId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the Branch table.
    /// </summary>
	[Table("[Branch]")]
	[Serializable()]
	public partial class Branch:Bindable
	{

 
	[ExplicitKey]
		public virtual string Code 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Name 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Url 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string AddressLine1 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string AddressLine2 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the ApiLog table.
    /// </summary>
	[Table("[ApiLog]")]
	[Serializable()]
	public partial class ApiLog:Bindable
	{

 
    [Key]
	public virtual int Id 
	{
            get { return Get<int>(); }
            set { Set(value); }
    }
	public virtual string FunctionName 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string XmlReq 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string JsonReq 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string XmlRes 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string JsonRes 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string Exception 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual DateTime? OrderDate 
	{
            get { return Get<DateTime?>(); }
            set { Set(value); }
    }
	public virtual string NID 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string UserId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string BranchId 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

    /// <summary>
    /// A class which represents the Sheet table.
    /// </summary>
	[Table("[Sheet]")]
	[Serializable()]
	public partial class Sheet:Bindable
	{

 
	public virtual string branch_name 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	public virtual string F2 
	{
            get { return Get<string>(); }
            set { Set(value); }
    }
	}

}
