// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CodeBeautify;
//
//    var welcome6 = Welcome6.FromJson(jsonString);

namespace TranslationEnglishRequest
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnglishRequest
    {
        [JsonProperty("soapenv:Envelope")]
        public SoapenvEnvelope SoapenvEnvelope { get; set; }
    }

    public partial class SoapenvEnvelope
    {
        [JsonProperty("@xmlns:soapenv")]
        public Uri XmlnsSoapenv { get; set; }

        [JsonProperty("@xmlns:nam")]
        public Uri XmlnsNam { get; set; }

        [JsonProperty("@xmlns:cal")]
        public Uri XmlnsCal { get; set; }

        [JsonProperty("soapenv:Header")]
        public SoapenvHeader SoapenvHeader { get; set; }

        [JsonProperty("soapenv:Body")]
        public SoapenvBody SoapenvBody { get; set; }
    }

    public partial class SoapenvBody
    {
        [JsonProperty("nam:NamesTranslatorRequest_elm")]
        public NamNamesTranslatorRequestElm NamNamesTranslatorRequestElm { get; set; }
    }

    public partial class NamNamesTranslatorRequestElm
    {
        [JsonProperty("cal:CallingData")]
        public CalCallingData CalCallingData { get; set; }

        [JsonProperty("nam:NamesTranslatorDescription")]
        public NamNamesTranslatorDescription NamNamesTranslatorDescription { get; set; }
    }

    public partial class CalCallingData
    {
        [JsonProperty("cal:ChannelId")]
        public string CalChannelId { get; set; }

        [JsonProperty("cal:RequestId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CalRequestId { get; set; }
    }

    public partial class NamNamesTranslatorDescription
    {
        [JsonProperty("nam:Type")]
        public string NamType { get; set; }

        [JsonProperty("nam:TXT")]
        public string NamTxt { get; set; }
    }

    public partial class SoapenvHeader
    {
        [JsonProperty("wsse:Security")]
        public WsseSecurity WsseSecurity { get; set; }
    }

    public partial class WsseSecurity
    {
        [JsonProperty("@xmlns:wsse")]
        public Uri XmlnsWsse { get; set; }

        [JsonProperty("wsse:UsernameToken")]
        public WsseUsernameToken WsseUsernameToken { get; set; }
    }

    public partial class WsseUsernameToken
    {
        [JsonProperty("@wsu:Id")]
        public string WsuId { get; set; }

        [JsonProperty("@xmlns:wsu")]
        public Uri XmlnsWsu { get; set; }

        [JsonProperty("wsse:Username")]
        public string WsseUsername { get; set; }

        [JsonProperty("wsse:Password")]
        public string WssePassword { get; set; }

        [JsonProperty("wsu:Created")]
        public DateTimeOffset WsuCreated { get; set; }
    }

    public partial class Welcome6
    {
        public static Welcome6 FromJson(string json) => JsonConvert.DeserializeObject<Welcome6>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome6 self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
