// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CodeBeautify;
//
//    var welcome7 = Welcome7.FromJson(jsonString);

namespace TranslationEnglishResponse
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnglishResponse
    {
        [JsonProperty("soapenv:Envelope")]
        public SoapenvEnvelope SoapenvEnvelope { get; set; }
    }

    public partial class SoapenvEnvelope
    {
        [JsonProperty("@xmlns:env")]
        public Uri XmlnsEnv { get; set; }

        [JsonProperty("@xmlns:soapenv")]
        public Uri XmlnsSoapenv { get; set; }

        [JsonProperty("soapenv:Header")]
        public SoapenvHeader SoapenvHeader { get; set; }

        [JsonProperty("soapenv:Body")]
        public SoapenvBody SoapenvBody { get; set; }
    }

    public partial class SoapenvBody
    {
        [JsonProperty("@xmlns:wsa")]
        public Uri XmlnsWsa { get; set; }

        [JsonProperty("tns:NamesTranslatorResponse_elm")]
        public TnsNamesTranslatorResponseElm TnsNamesTranslatorResponseElm { get; set; }
    }

    public partial class TnsNamesTranslatorResponseElm
    {
        [JsonProperty("@xmlns:mime")]
        public Uri XmlnsMime { get; set; }

        [JsonProperty("@xmlns:soap12")]
        public Uri XmlnsSoap12 { get; set; }

        [JsonProperty("@xmlns:plnk")]
        public Uri XmlnsPlnk { get; set; }

        [JsonProperty("@xmlns:soapenc")]
        public Uri XmlnsSoapenc { get; set; }

        [JsonProperty("@xmlns:wsdl")]
        public Uri XmlnsWsdl { get; set; }

        [JsonProperty("@xmlns:http")]
        public Uri XmlnsHttp { get; set; }

        [JsonProperty("@xmlns:tm")]
        public Uri XmlnsTm { get; set; }

        [JsonProperty("@xmlns:client")]
        public Uri XmlnsClient { get; set; }

        [JsonProperty("@xmlns:soap")]
        public Uri XmlnsSoap { get; set; }

        [JsonProperty("@xmlns:tns")]
        public Uri XmlnsTns { get; set; }

        [JsonProperty("@xmlns")]
        public Uri Xmlns { get; set; }

        [JsonProperty("cal:CallingData")]
        public CalCallingData CalCallingData { get; set; }

        [JsonProperty("tns:ResponseStatus")]
        public TnsResponseStatus TnsResponseStatus { get; set; }

        [JsonProperty("tns:ResponseData")]
        public TnsResponseData TnsResponseData { get; set; }
    }

    public partial class CalCallingData
    {
        [JsonProperty("@xmlns:cal")]
        public Uri XmlnsCal { get; set; }

        [JsonProperty("cal:ChannelId")]
        public string CalChannelId { get; set; }

        [JsonProperty("cal:RequestId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CalRequestId { get; set; }
    }

    public partial class TnsResponseData
    {
        [JsonProperty("tns:TransTxtResult")]
        public string TnsTransTxtResult { get; set; }
    }

    public partial class TnsResponseStatus
    {
        [JsonProperty("tns:Code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TnsCode { get; set; }

        [JsonProperty("tns:Description")]
        public string TnsDescription { get; set; }
    }

    public partial class SoapenvHeader
    {
        [JsonProperty("@xmlns:wsa")]
        public Uri XmlnsWsa { get; set; }

        [JsonProperty("wsa:MessageID")]
        public string WsaMessageId { get; set; }

        [JsonProperty("wsa:ReplyTo")]
        public WsaReplyTo WsaReplyTo { get; set; }

        [JsonProperty("wsa:FaultTo")]
        public WsaFaultTo WsaFaultTo { get; set; }
    }

    public partial class WsaFaultTo
    {
        [JsonProperty("wsa:Address")]
        public Uri WsaAddress { get; set; }
    }

    public partial class WsaReplyTo
    {
        [JsonProperty("wsa:Address")]
        public Uri WsaAddress { get; set; }

        [JsonProperty("wsa:ReferenceParameters")]
        public WsaReferenceParameters WsaReferenceParameters { get; set; }
    }

    public partial class WsaReferenceParameters
    {
        [JsonProperty("instra:tracking.ecid")]
        public InstraTracking InstraTrackingEcid { get; set; }

        [JsonProperty("instra:tracking.FlowEventId")]
        public InstraTracking InstraTrackingFlowEventId { get; set; }

        [JsonProperty("instra:tracking.FlowId")]
        public InstraTracking InstraTrackingFlowId { get; set; }

        [JsonProperty("instra:tracking.CorrelationFlowId")]
        public InstraTracking InstraTrackingCorrelationFlowId { get; set; }

        [JsonProperty("instra:tracking.quiescing.SCAEntityId")]
        public InstraTracking InstraTrackingQuiescingScaEntityId { get; set; }
    }

    public partial class InstraTracking
    {
        [JsonProperty("@xmlns:instra")]
        public Uri XmlnsInstra { get; set; }

        [JsonProperty("#text")]
        public string Text { get; set; }
    }

    public partial class EnglishResponse
    {
        public static EnglishResponse FromJson(string json) => JsonConvert.DeserializeObject<EnglishResponse>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this EnglishResponse self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
