/*
    Kishny POS - remove DEV_Serial from POS save hot path

    Production intent:
      DEV_Serial is a legacy display/text field only. It must not allocate,
      lock, serialize, validate, join, or order POS save/accounting logic.

    What this script changes:
      - Recreates dbo.usp_POS_SaveTransaction after replacing the old
        POS_DEVSerialAllocator block with a cheap text assignment:
            yyyyMMdd + '-' + Double_Entry_Vouchers_ID
      - Removes the DEV_Serial allocation timing stage from the procedure.
      - Captures the original procedure text for rollback.

    sqlcmd rollback:
      sqlcmd -S . -d Cash -E -v DevSerialAction=ROLLBACK -i 97_POS_DEVSerial_RemoveFromHotPath.sql

    What this script does not change:
      - Accounting amounts.
      - Notes_ID / Transaction_ID links.
      - Double_Entry_Vouchers_ID / DEV_ID_Line_No.
      - Existing historical DEV_Serial values.
      - Any index/constraint, unless reviewed separately.

    SQL Server compatibility: SQL Server 2012.
*/

SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

IF DB_NAME() IN (N'master', N'model', N'msdb', N'tempdb')
BEGIN
    RAISERROR('Refusing to run in a system database.', 16, 1);
    RETURN;
END;

IF OBJECT_ID(N'dbo.usp_POS_SaveTransaction', N'P') IS NULL
BEGIN
    RAISERROR('dbo.usp_POS_SaveTransaction was not found.', 16, 1);
    RETURN;
END;

IF OBJECT_ID(N'dbo.POS_DEVSerialHotPathRollback', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.POS_DEVSerialHotPathRollback
    (
        BackupId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_POS_DEVSerialHotPathRollback PRIMARY KEY,
        CreatedAt DATETIME NOT NULL CONSTRAINT DF_POS_DEVSerialHotPathRollback_CreatedAt DEFAULT(GETDATE()),
        DatabaseName SYSNAME NOT NULL,
        ProcedureName SYSNAME NOT NULL,
        DefinitionText NVARCHAR(MAX) NOT NULL,
        Notes NVARCHAR(4000) NULL
    );
END;

DECLARE @Definition NVARCHAR(MAX);
DECLARE @CreateDefinition NVARCHAR(MAX);
DECLARE @Replacement NVARCHAR(MAX);
DECLARE @Action NVARCHAR(20);
DECLARE @Start INT;
DECLARE @End INT;
DECLARE @StartMarker NVARCHAR(4000);
DECLARE @EndMarker NVARCHAR(4000);

SET @Action = UPPER(LTRIM(RTRIM(N'$(DevSerialAction)')));
IF @Action LIKE N'$%' OR @Action = N''
    SET @Action = N'APPLY';

IF @Action NOT IN (N'APPLY', N'ROLLBACK')
BEGIN
    RAISERROR('Invalid DevSerialAction. Use APPLY or ROLLBACK.', 16, 1);
    RETURN;
END;

SELECT @Definition = OBJECT_DEFINITION(OBJECT_ID(N'dbo.usp_POS_SaveTransaction'));

IF @Definition IS NULL
BEGIN
    RAISERROR('Unable to read dbo.usp_POS_SaveTransaction definition.', 16, 1);
    RETURN;
END;

IF NOT EXISTS
(
    SELECT 1
    FROM dbo.POS_DEVSerialHotPathRollback
    WHERE ProcedureName = N'usp_POS_SaveTransaction'
)
BEGIN
    INSERT INTO dbo.POS_DEVSerialHotPathRollback(DatabaseName, ProcedureName, DefinitionText, Notes)
    VALUES (DB_NAME(), N'usp_POS_SaveTransaction', @Definition, N'Before removing DEV_Serial allocator from POS save hot path.');
END;

IF @Action = N'ROLLBACK'
BEGIN
    SELECT TOP (1)
        @CreateDefinition = DefinitionText
    FROM dbo.POS_DEVSerialHotPathRollback
    WHERE ProcedureName = N'usp_POS_SaveTransaction'
    ORDER BY BackupId DESC;

    IF @CreateDefinition IS NULL
    BEGIN
        RAISERROR('No rollback definition was found in dbo.POS_DEVSerialHotPathRollback.', 16, 1);
        RETURN;
    END;

    DROP PROCEDURE dbo.usp_POS_SaveTransaction;
    EXEC (@CreateDefinition);
    PRINT 'dbo.usp_POS_SaveTransaction restored from dbo.POS_DEVSerialHotPathRollback.';
    RETURN;
END;

PRINT 'Checking for indexes/constraints that include DEV_Serial.';
SELECT
    IndexName = i.name,
    i.type_desc,
    i.is_primary_key,
    i.is_unique,
    i.is_unique_constraint
FROM sys.indexes i
WHERE i.object_id = OBJECT_ID(N'dbo.DOUBLE_ENTREY_VOUCHERS')
  AND EXISTS
  (
      SELECT 1
      FROM sys.index_columns ic
      INNER JOIN sys.columns c
          ON c.object_id = ic.object_id
         AND c.column_id = ic.column_id
      WHERE ic.object_id = i.object_id
        AND ic.index_id = i.index_id
        AND c.name = N'DEV_Serial'
  );

SET @StartMarker = N'        /*
            DEV_Serial used to be generated by COUNT(DISTINCT Double_Entry_Vouchers_ID)';
SET @EndMarker = N'        SELECT
            @BranchName = NULLIF';

SET @Start = CHARINDEX(@StartMarker, @Definition);
SET @End = CHARINDEX(@EndMarker, @Definition, CASE WHEN @Start > 0 THEN @Start ELSE 1 END);

IF @Start = 0 OR @End = 0 OR @End <= @Start
BEGIN
    IF @Definition LIKE N'%CONVERT(CHAR(8), @TransactionDate, 112) + N''-'' +%CONVERT(NVARCHAR(20), @DevID)%'
    BEGIN
        PRINT 'dbo.usp_POS_SaveTransaction already uses cheap DEV_Serial text and has no allocator block.';
        RETURN;
    END;

    RAISERROR('Could not find the old DEV_Serial allocator block and the cheap text replacement was not detected.', 16, 1);
    RETURN;
END;

SET @Replacement = N'        /*
            DEV_Serial is a legacy text/display field only. It is not a
            business key, not unique, not gap-free, and must not serialize POS
            save. Keep a cheap readable value without touching allocator tables.
        */
        SET @DevSerial =
            CONVERT(CHAR(8), @TransactionDate, 112) + N''-'' +
            CONVERT(NVARCHAR(20), @DevID);

';

SET @CreateDefinition =
    SUBSTRING(@Definition, 1, @Start - 1) +
    @Replacement +
    SUBSTRING(@Definition, @End, LEN(@Definition));

IF @CreateDefinition NOT LIKE N'%CREATE PROCEDURE dbo.usp_POS_SaveTransaction%'
BEGIN
    RAISERROR('Unexpected procedure definition format. Expected CREATE PROCEDURE dbo.usp_POS_SaveTransaction.', 16, 1);
    RETURN;
END;

DROP PROCEDURE dbo.usp_POS_SaveTransaction;
EXEC (@CreateDefinition);

PRINT 'dbo.usp_POS_SaveTransaction recreated. DEV_Serial no longer uses POS_DEVSerialAllocator or a timing allocation stage.';
