//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdditionalItem()
        {
            this.AdditionalItemsGroups = new HashSet<AdditionalItemsGroup>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ItemUnitId { get; set; }
        public Nullable<double> Equivalent { get; set; }
        public Nullable<decimal> DoublePrice { get; set; }
        public Nullable<decimal> ExtraPrice { get; set; }
        public Nullable<decimal> ShortagePrice { get; set; }
        public Nullable<decimal> ExtraQuantity { get; set; }
        public Nullable<decimal> DoubleQuantity { get; set; }
        public Nullable<decimal> ShortageQuantity { get; set; }
        public Nullable<int> ItemPriceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalItemsGroup> AdditionalItemsGroups { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual ItemPrice ItemPrice { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
