//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingCompaign
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<decimal> Target { get; set; }
        public Nullable<decimal> ExpectedSales { get; set; }
        public Nullable<decimal> ActualSales { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ResposibleId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ProductGroupId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public bool IsDeleted { get; set; }
        public string Image { get; set; }
    }
}
