//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSalesInvoiceDetail
    {
        public int Id { get; set; }
        public Nullable<int> CarServiceId { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public Nullable<decimal> ServiceDiscountValue { get; set; }
        public Nullable<double> ServiceDiscountPercentage { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ServiceNetTotal { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
    
        public virtual CarSalesInvoice CarSalesInvoice { get; set; }
        public virtual CarService CarService { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
