//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public double QTY { get; set; }
        public decimal PriceBeforeDiscount { get; set; }
        public decimal PriceAfterDiscount { get; set; }
        public decimal DiscountAmount { get; set; }
        public double DiscountPercentage { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int ItemPriceId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual ItemPrice ItemPrice { get; set; }
    }
}
