//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReceiptVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashReceiptVoucher()
        {
            this.SalesInvoiceActualPayments = new HashSet<SalesInvoiceActualPayment>();
            this.CashReceiptVoucherPropertyContractBatches = new HashSet<CashReceiptVoucherPropertyContractBatch>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> MoneyAmount { get; set; }
        public int SourceTypeId { get; set; }
        public string OtherSourceName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CashBoxId { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<int> DirectRevenueId { get; set; }
        public Nullable<int> ShareholderId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<bool> IsInvoiceSelected { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ChartOfAccountId { get; set; }
        public Nullable<int> CashReceiptPaymentMethodId { get; set; }
        public string VendorReceiptNumber { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> ChildrenId { get; set; }
        public Nullable<int> ElderId { get; set; }
        public string IssuedPerson { get; set; }
        public Nullable<int> PropertyContractId { get; set; }
        public Nullable<int> RenterId { get; set; }
        public Nullable<decimal> ElectricityBillValue { get; set; }
        public Nullable<decimal> GasBillValue { get; set; }
        public Nullable<decimal> ViolationBillValue { get; set; }
        public Nullable<int> PropertyContractTerminationId { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual Department Department { get; set; }
        public virtual DirectRevenue DirectRevenue { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual ShareHolder ShareHolder { get; set; }
        public virtual Techanician Techanician { get; set; }
        public virtual ChartOfAccount ChartOfAccount1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceActualPayment> SalesInvoiceActualPayments { get; set; }
        public virtual CashReceiptPaymentMethod CashReceiptPaymentMethod { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Elder Elder { get; set; }
        public virtual PropertyContract PropertyContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashReceiptVoucherPropertyContractBatch> CashReceiptVoucherPropertyContractBatches { get; set; }
        public virtual Child Child { get; set; }
        public virtual PropertyContractTermination PropertyContractTermination { get; set; }
        public virtual CashReceiptSourceType CashReceiptSourceType { get; set; }
    }
}
