//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CarEntrances = new HashSet<CarEntrance>();
            this.CarSalesInvoices = new HashSet<CarSalesInvoice>();
            this.Carts = new HashSet<Cart>();
            this.CarWorkOrders = new HashSet<CarWorkOrder>();
            this.CashIssueVouchers = new HashSet<CashIssueVoucher>();
            this.CashReceiptVouchers = new HashSet<CashReceiptVoucher>();
            this.ChequeIssues = new HashSet<ChequeIssue>();
            this.ChequeReceipts = new HashSet<ChequeReceipt>();
            this.CustomerMessages = new HashSet<CustomerMessage>();
            this.CustomerOpenningBalances = new HashSet<CustomerOpenningBalance>();
            this.CustomerReps = new HashSet<CustomerRep>();
            this.ItemPriceRates = new HashSet<ItemPriceRate>();
            this.Maintenances = new HashSet<Maintenance>();
            this.Orders = new HashSet<Order>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.SalesQuotations = new HashSet<SalesQuotation>();
            this.SalesReturns = new HashSet<SalesReturn>();
            this.WishLists = new HashSet<WishList>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.RoomBookings = new HashSet<RoomBooking>();
            this.MealReservations = new HashSet<MealReservation>();
            this.DayUseReservations = new HashSet<DayUseReservation>();
            this.HotelManagementCarEntries = new HashSet<HotelManagementCarEntry>();
            this.RoomLeavePermissions = new HashSet<RoomLeavePermission>();
            this.Surgeries = new HashSet<Surgery>();
            this.PosCustomers = new HashSet<PosCustomer>();
            this.PartyBookings = new HashSet<PartyBooking>();
            this.PropertyRenters = new HashSet<PropertyRenter>();
            this.ServiceInvoices = new HashSet<ServiceInvoice>();
            this.DebitAndCreditNotifications = new HashSet<DebitAndCreditNotification>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CustomersGroupId { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string TaxNumber { get; set; }
        public string WorkNature { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> AllowCreditLimit { get; set; }
        public Nullable<decimal> CreditLimitAmount { get; set; }
        public Nullable<double> CreditLimitPeriod { get; set; }
        public Nullable<decimal> ObDebit { get; set; }
        public Nullable<decimal> ObCredit { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string PlayerId { get; set; }
        public Nullable<int> SourceTypeId { get; set; }
        public string IdImage { get; set; }
        public Nullable<bool> Language { get; set; }
        public Nullable<bool> IncludeFees { get; set; }
        public Nullable<bool> IsBranch { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string BuildingNo { get; set; }
        public string PostOfficeBox { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string VATNumber { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> FieldsCodingId { get; set; }
        public string NationalId { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<bool> InsuranceCompany { get; set; }
        public Nullable<double> InsuranceCompanyPercentage { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarEntrance> CarEntrances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarSalesInvoice> CarSalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarWorkOrder> CarWorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashIssueVoucher> CashIssueVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashReceiptVoucher> CashReceiptVouchers { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeIssue> ChequeIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeReceipt> ChequeReceipts { get; set; }
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual CustomersGroup CustomersGroup { get; set; }
        public virtual CustomerSourceType CustomerSourceType { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual Nationality Nationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMessage> CustomerMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOpenningBalance> CustomerOpenningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRep> CustomerReps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPriceRate> ItemPriceRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotation> SalesQuotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual FieldsCoding FieldsCoding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealReservation> MealReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayUseReservation> DayUseReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelManagementCarEntry> HotelManagementCarEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomLeavePermission> RoomLeavePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surgery> Surgeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosCustomer> PosCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyBooking> PartyBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRenter> PropertyRenters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInvoice> ServiceInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitAndCreditNotification> DebitAndCreditNotifications { get; set; }
    }
}
