//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitAndCreditNotification
    {
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DebitAndCreditNotificationTypeId { get; set; }
        public int SourceTypeId { get; set; }
        public Nullable<int> RepId { get; set; }
        public Nullable<decimal> TotalMoneyAmount { get; set; }
        public Nullable<decimal> MoneyAmount { get; set; }
        public Nullable<decimal> VATValue { get; set; }
        public Nullable<double> VATPercentage { get; set; }
        public Nullable<int> DebitId { get; set; }
        public Nullable<int> CreditId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<int> DirectRevenueId { get; set; }
        public Nullable<int> ShareholderId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> ChildrenId { get; set; }
        public Nullable<int> ElderId { get; set; }
        public string IssuedPerson { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> RenterId { get; set; }
        public string QrCodeData { get; set; }
        public string QrCodeDataPath { get; set; }
        public byte[] QrCodeImage { get; set; }
        public Nullable<int> zatcaStatus { get; set; }
        public Nullable<double> InvoiceTypeCodeID { get; set; }
        public string InvoiceTypeCodename { get; set; }
        public string AdditionalDocumentReferencePIH { get; set; }
        public string InvoiceDocumentReferenceID { get; set; }
        public string AdditionalDocumentReferenceICVUUID { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public Nullable<System.DateTime> LatestDeliveryDate { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public Nullable<double> Transaction_ID { get; set; }
        public string warrningmessage { get; set; }
        public Nullable<double> PaymentMeansCode { get; set; }
        public string InstructionNote { get; set; }
        public string Iban { get; set; }
        public string paymentnote { get; set; }
        public string AdditionalStreetName { get; set; }
        public string PlotIdentification { get; set; }
        public string CountrySubentity { get; set; }
        public string IdentificationCode { get; set; }
        public Nullable<System.DateTime> last_changed { get; set; }
        public string Identificationid { get; set; }
        public string schemeID { get; set; }
        public Nullable<double> TaxCategoryPercent { get; set; }
        public string TaxCategoryID { get; set; }
        public Nullable<int> Export { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string branch_name { get; set; }
        public string branchname { get; set; }
        public string DocumentCurrencyCode { get; set; }
        public string TaxCurrencyCode { get; set; }
        public Nullable<double> allowancechargeAmount { get; set; }
        public string allowancechargeAllowanceChargeReason { get; set; }
        public Nullable<double> allowancechargeTaxCategoryid { get; set; }
        public Nullable<double> allowancechargeTaxCategoryPercent { get; set; }
        public Nullable<double> LegalMonetaryTotalPayableAmount { get; set; }
        public Nullable<double> LegalMonetaryTotalPrepaidAmount { get; set; }
        public string TableName { get; set; }
        public string ErrorMessageS { get; set; }
        public Nullable<bool> InvoiceType { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual ChartOfAccount ChartOfAccount1 { get; set; }
        public virtual ChartOfAccount ChartOfAccount2 { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DebitAndCreditNotificationSourceType DebitAndCreditNotificationSourceType { get; set; }
        public virtual DebitAndCreditNotificationType DebitAndCreditNotificationType { get; set; }
        public virtual Department Department { get; set; }
        public virtual DirectRevenue DirectRevenue { get; set; }
        public virtual Elder Elder { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual PropertyRenter PropertyRenter { get; set; }
        public virtual ShareHolder ShareHolder { get; set; }
        public virtual Techanician Techanician { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Child Child { get; set; }
    }
}
