//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContractVacation
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeContractId { get; set; }
        public Nullable<int> SalaryItemId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual SalaryItem SalaryItem { get; set; }
        public virtual EmployeeContract EmployeeContract { get; set; }
    }
}
