//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeContract()
        {
            this.EmployeeContractAnnualIncreases = new HashSet<EmployeeContractAnnualIncrease>();
            this.EmployeeContractEndOfServices = new HashSet<EmployeeContractEndOfService>();
            this.EmployeeContractSalaryItems = new HashSet<EmployeeContractSalaryItem>();
            this.EmployeeContractVacations = new HashSet<EmployeeContractVacation>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> ContractPeriodNum { get; set; }
        public Nullable<int> ContractPeriodTypeId { get; set; }
        public Nullable<decimal> TestPeriodNum { get; set; }
        public Nullable<int> TestPeriodTypeId { get; set; }
        public Nullable<System.DateTime> ContractStartTime { get; set; }
        public Nullable<System.DateTime> ContractEndTime { get; set; }
        public Nullable<int> ContractJobId { get; set; }
        public Nullable<int> ContractsTypeId { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public Nullable<int> ContractsStatusId { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> AdministrativeDepartmentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EmployeeInsuranceCategoryId { get; set; }
        public string InsuranceNum { get; set; }
        public Nullable<bool> EmployeeHasInsurance { get; set; }
        public Nullable<bool> WifeHasInsurance { get; set; }
        public Nullable<bool> EmployeeHasTicket { get; set; }
        public Nullable<bool> WifeHasTicket { get; set; }
        public Nullable<bool> RelativesHasTicket { get; set; }
        public Nullable<decimal> TicketsNum { get; set; }
        public Nullable<decimal> TicketsTotalValue { get; set; }
        public Nullable<int> WifeInsuranceCategoryId { get; set; }
        public Nullable<decimal> SalaryFixedIncreaseValue { get; set; }
        public Nullable<double> SalaryIncreaseRatio { get; set; }
        public Nullable<decimal> VacationSalaryIncreaseValue { get; set; }
        public Nullable<decimal> VacationDuePeriodNum { get; set; }
        public Nullable<int> VacationDuePeriodTypeId { get; set; }
        public Nullable<decimal> VacationEquivalentWorkPeriodNum { get; set; }
        public Nullable<int> VacationEquivalentWorkPeriodId { get; set; }
        public Nullable<decimal> VacationPeriodNum { get; set; }
        public Nullable<int> VacationPeriodTypeId { get; set; }
        public Nullable<decimal> EmployeeTotalSalary { get; set; }
        public string Sequence { get; set; }
    
        public virtual ContractsStatu ContractsStatu { get; set; }
        public virtual ContractsType ContractsType { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual InsuranceCategory InsuranceCategory { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContractAnnualIncrease> EmployeeContractAnnualIncreases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContractEndOfService> EmployeeContractEndOfServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContractSalaryItem> EmployeeContractSalaryItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContractVacation> EmployeeContractVacations { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
