//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeVacationOpeningBalanceDetail
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> VacationBalance { get; set; }
        public Nullable<double> VacationWithoutSalary { get; set; }
        public Nullable<double> Absence { get; set; }
        public string StartDateHijri { get; set; }
        public string EndDateHijri { get; set; }
        public Nullable<int> SelectedId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeVacationOpeningBalance EmployeeVacationOpeningBalance { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
