//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayrollIssueDetail
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> HrDepartmentId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<System.DateTime> FirstWorkDate { get; set; }
        public Nullable<System.DateTime> LastWorkDate { get; set; }
        public Nullable<int> NoOfWorkingDays { get; set; }
        public Nullable<int> AbsenceDays { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public Nullable<decimal> SalaryItem1 { get; set; }
        public Nullable<decimal> SalaryItem2 { get; set; }
        public Nullable<decimal> SalaryItem3 { get; set; }
        public Nullable<decimal> SalaryItem4 { get; set; }
        public Nullable<decimal> SalaryItem5 { get; set; }
        public Nullable<decimal> SalaryItem6 { get; set; }
        public Nullable<decimal> SalaryItem7 { get; set; }
        public Nullable<decimal> SalaryItem8 { get; set; }
        public Nullable<decimal> SalaryItem9 { get; set; }
        public Nullable<decimal> SalaryItem10 { get; set; }
        public Nullable<decimal> SalaryItem11 { get; set; }
        public Nullable<decimal> SalaryItem12 { get; set; }
        public Nullable<decimal> SalaryItem13 { get; set; }
        public Nullable<decimal> SalaryItem14 { get; set; }
        public Nullable<decimal> SalaryItem15 { get; set; }
        public Nullable<decimal> SalaryItem16 { get; set; }
        public Nullable<decimal> SalaryItem17 { get; set; }
        public Nullable<decimal> SalaryItem18 { get; set; }
        public Nullable<decimal> SalaryItem19 { get; set; }
        public Nullable<decimal> SalaryItem20 { get; set; }
        public Nullable<decimal> SalaryItem21 { get; set; }
        public Nullable<decimal> SalaryItem22 { get; set; }
        public Nullable<decimal> SalaryItem23 { get; set; }
        public Nullable<decimal> SalaryItem24 { get; set; }
        public Nullable<decimal> SalaryItem25 { get; set; }
        public Nullable<decimal> SalaryItem26 { get; set; }
        public Nullable<decimal> SalaryItem27 { get; set; }
        public Nullable<decimal> SalaryItem28 { get; set; }
        public Nullable<decimal> SalaryItem29 { get; set; }
        public Nullable<decimal> SalaryItem30 { get; set; }
        public Nullable<decimal> SalaryItem31 { get; set; }
        public Nullable<decimal> SalaryItem32 { get; set; }
        public Nullable<decimal> SalaryItem33 { get; set; }
        public Nullable<decimal> AdvancedExpenses { get; set; }
        public decimal TotalOvertime { get; set; }
        public decimal TotalReward { get; set; }
        public decimal TotalPenalty { get; set; }
        public decimal TotalDueItems { get; set; }
        public decimal TotalDeductionItems { get; set; }
        public decimal NetSalary { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsIssued { get; set; }
        public Nullable<decimal> BorrowValue { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual HrDepartment HrDepartment { get; set; }
        public virtual EmployeePayrollIssue EmployeePayrollIssue { get; set; }
        public virtual Job Job { get; set; }
        public virtual Nationality Nationality { get; set; }
    }
}
