//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryItem
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int SalaryItemId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalaryItem SalaryItem { get; set; }
    }
}
