//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesGroup
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string Image { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ERPUser ERPUser { get; set; }
    }
}
