//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOpenningBalance
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<decimal> PaidAllowancesAccumulated { get; set; }
        public Nullable<decimal> EmpVacationAccumulated { get; set; }
        public Nullable<decimal> TravelingTicketsAccumulated { get; set; }
        public Nullable<decimal> EndOfServiceAccumulated { get; set; }
        public Nullable<decimal> EmployeeReceivableValue { get; set; }
        public Nullable<decimal> DueSalariesValue { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
