//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfServiceSalaryItem
    {
        public int Id { get; set; }
        public Nullable<int> EndOfServiceId { get; set; }
        public Nullable<int> SalaryItemId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalaryItem SalaryItem { get; set; }
        public virtual EndOfServiceRewardAccount EndOfServiceRewardAccount { get; set; }
    }
}
