//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAmortizationDistribution
    {
        public int Id { get; set; }
        public Nullable<int> PrepaidExpenseDetailId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> ExpenseAmortizationId { get; set; }
        public Nullable<bool> IsSelectedAmortization { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ExpenseAmortization ExpenseAmortization { get; set; }
        public virtual PrepaidExpenseDetail PrepaidExpenseDetail { get; set; }
    }
}
