//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragmentationVoucherDetail
    {
        public int Id { get; set; }
        public int MainDocId { get; set; }
        public int ItemId { get; set; }
        public double Qty { get; set; }
        public int ItemUnitId { get; set; }
        public double UnitEquivalent { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ItemPriceId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<double> DiscountPerc { get; set; }
        public Nullable<int> WareHouseId { get; set; }
        public Nullable<double> WarrantyPeriod { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> PatchId { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<double> RemainQty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> ItemDirectExpenses { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<int> ExtraTypeId { get; set; }
    
        public virtual FragmentationVoucher FragmentationVoucher { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual ItemPrice ItemPrice { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Patch Patch { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual SystemPage SystemPage { get; set; }
    }
}
