//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    
    public partial class GetRoomLeavePermissionInDate_Result1
    {
        public string RoomLeaveDocumentNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public decimal Insurance { get; set; }
        public decimal InsuranceDeduction { get; set; }
        public decimal Remain { get; set; }
        public string BookingDocumentNumber { get; set; }
        public Nullable<System.DateTime> BookingStartDate { get; set; }
        public Nullable<System.DateTime> BookingEndDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string BuildingArName { get; set; }
        public string RoomCode { get; set; }
        public string CustomerArName { get; set; }
        public string CustomerMobile { get; set; }
        public string DepartmentArName { get; set; }
        public string EmployeeArName { get; set; }
    }
}
