//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    
    public partial class GetUserPriviledges_AllPages_privileged_Result1
    {
        public Nullable<int> PageId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string actionsArName { get; set; }
        public Nullable<int> Privileged { get; set; }
        public string C_SystemPage_ArName { get; set; }
    }
}
