//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.DepartmentItems = new HashSet<DepartmentItem>();
            this.InventoryVoucherDetails = new HashSet<InventoryVoucherDetail>();
            this.ItemComponents = new HashSet<ItemComponent>();
            this.ItemCostPrices = new HashSet<ItemCostPrice>();
            this.ItemPrices = new HashSet<ItemPrice>();
            this.ItemQuantities = new HashSet<ItemQuantity>();
            this.ItemVendors = new HashSet<ItemVendor>();
            this.Maintenances = new HashSet<Maintenance>();
            this.ManufacturingRequestItems = new HashSet<ManufacturingRequestItem>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.PurchaseQuotationDetails = new HashSet<PurchaseQuotationDetail>();
            this.PurchaseRequestDetails = new HashSet<PurchaseRequestDetail>();
            this.PurchaseReturnsDetails = new HashSet<PurchaseReturnsDetail>();
            this.PurchaseSaleSerialNumbers = new HashSet<PurchaseSaleSerialNumber>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesQuotationDetails = new HashSet<SalesQuotationDetail>();
            this.SalesReturnsDetails = new HashSet<SalesReturnsDetail>();
            this.StockIssueVoucherDetails = new HashSet<StockIssueVoucherDetail>();
            this.StockLossesVoucherDetails = new HashSet<StockLossesVoucherDetail>();
            this.StockReceiptVoucherDetails = new HashSet<StockReceiptVoucherDetail>();
            this.StockTransferVoucherDetails = new HashSet<StockTransferVoucherDetail>();
            this.UpdatedTransactionDetails = new HashSet<UpdatedTransactionDetail>();
            this.WarehouseOBDetails = new HashSet<WarehouseOBDetail>();
            this.ItemImages = new HashSet<ItemImage>();
            this.AdditionalItems = new HashSet<AdditionalItem>();
            this.CarServiceDetails = new HashSet<CarServiceDetail>();
            this.SalesInvoiceItemDistributions = new HashSet<SalesInvoiceItemDistribution>();
            this.Patches = new HashSet<Patch>();
            this.AssemblyVouchers = new HashSet<AssemblyVoucher>();
            this.AssemblyVoucherDetails = new HashSet<AssemblyVoucherDetail>();
            this.FragmentationVouchers = new HashSet<FragmentationVoucher>();
            this.FragmentationVoucherDetails = new HashSet<FragmentationVoucherDetail>();
            this.MealReservationDetails = new HashSet<MealReservationDetail>();
            this.Orders = new HashSet<Order>();
            this.OrderItems = new HashSet<OrderItem>();
            this.ExaminationMedicines = new HashSet<ExaminationMedicine>();
            this.SurgeryMedicines = new HashSet<SurgeryMedicine>();
            this.ItemsPrintBarcodeQueues = new HashSet<ItemsPrintBarcodeQueue>();
            this.AlternativeItems = new HashSet<AlternativeItem>();
            this.AlternativeItems1 = new HashSet<AlternativeItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<int> OrderLimit { get; set; }
        public int ItemGroupId { get; set; }
        public int ItemTypeId { get; set; }
        public Nullable<bool> HasWarranty { get; set; }
        public Nullable<bool> HasExpiry { get; set; }
        public Nullable<int> WarrantyDays { get; set; }
        public Nullable<int> WarrantyMonths { get; set; }
        public Nullable<int> WarrantyYears { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public string IdOnWebSite { get; set; }
        public string ProductNo { get; set; }
        public Nullable<double> VirtualQuantity { get; set; }
        public string KrName { get; set; }
        public string ArNotes { get; set; }
        public string KrNotes { get; set; }
        public string EnDetails { get; set; }
        public string ArDetails { get; set; }
        public string KrDetails { get; set; }
        public Nullable<bool> IsAccessory { get; set; }
        public Nullable<bool> HasAccessory { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> FieldsCodingId { get; set; }
        public Nullable<bool> NotIncludeValueAddedTax { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentItem> DepartmentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryVoucherDetail> InventoryVoucherDetails { get; set; }
        public virtual ItemGroup ItemGroup { get; set; }
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemComponent> ItemComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCostPrice> ItemCostPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemQuantity> ItemQuantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemVendor> ItemVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturingRequestItem> ManufacturingRequestItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseQuotationDetail> PurchaseQuotationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnsDetail> PurchaseReturnsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSaleSerialNumber> PurchaseSaleSerialNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationDetail> SalesQuotationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturnsDetail> SalesReturnsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockIssueVoucherDetail> StockIssueVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockLossesVoucherDetail> StockLossesVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReceiptVoucherDetail> StockReceiptVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransferVoucherDetail> StockTransferVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdatedTransactionDetail> UpdatedTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOBDetail> WarehouseOBDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemImage> ItemImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalItem> AdditionalItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarServiceDetail> CarServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceItemDistribution> SalesInvoiceItemDistributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patch> Patches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyVoucher> AssemblyVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyVoucherDetail> AssemblyVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FragmentationVoucher> FragmentationVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FragmentationVoucherDetail> FragmentationVoucherDetails { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual FieldsCoding FieldsCoding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealReservationDetail> MealReservationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationMedicine> ExaminationMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryMedicine> SurgeryMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsPrintBarcodeQueue> ItemsPrintBarcodeQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternativeItem> AlternativeItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternativeItem> AlternativeItems1 { get; set; }
    }
}
