//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.LessonImages = new HashSet<LessonImage>();
            this.RegisterAttendanceAndAbsenceDetails = new HashSet<RegisterAttendanceAndAbsenceDetail>();
            this.RegisterAttendanceAndAbsences = new HashSet<RegisterAttendanceAndAbsence>();
            this.EducationalSubjects = new HashSet<EducationalSubject>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<int> EducationalSubjectId { get; set; }
        public string CognitiveGoal { get; set; }
        public string EmotionalGoal { get; set; }
        public string Verse { get; set; }
        public string LessonContent { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public string LecturerName { get; set; }
        public string VideoLink { get; set; }
        public string PDFLink { get; set; }
        public string PowerPointLink { get; set; }
    
        public virtual EducationalSubject EducationalSubject { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonImage> LessonImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterAttendanceAndAbsenceDetail> RegisterAttendanceAndAbsenceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterAttendanceAndAbsence> RegisterAttendanceAndAbsences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalSubject> EducationalSubjects { get; set; }
    }
}
