//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int Id { get; set; }
        public Nullable<int> MaintenanceTypeID { get; set; }
        public string ServicelNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ClientProblem { get; set; }
        public string Appearance { get; set; }
        public Nullable<int> DamagedItemsId { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> SalesInvoiceId { get; set; }
        public Nullable<System.DateTime> SalesInvoiceDate { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> PurchaseInvoiceId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string AttachedFiles { get; set; }
        public string Image { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InvoiceNumberOfVendor { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual Item Item { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
