//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturingRequestItemDetail
    {
        public int Id { get; set; }
        public int ManufacturingRequestd { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public int UnitId { get; set; }
        public double Qty { get; set; }
        public Nullable<int> WareHouseId { get; set; }
        public bool Received { get; set; }
    
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual ManufacturingRequest ManufacturingRequest { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
