//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyRenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyRenter()
        {
            this.PropertyNotifications = new HashSet<PropertyNotification>();
            this.PropertyContracts = new HashSet<PropertyContract>();
            this.PropertyRenterImages = new HashSet<PropertyRenterImage>();
            this.PropertyContractTerminations = new HashSet<PropertyContractTermination>();
            this.Orders = new HashSet<Order>();
            this.DebitAndCreditNotifications = new HashSet<DebitAndCreditNotification>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> RenterTypeId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string NationalNo { get; set; }
        public Nullable<System.DateTime> NationalExpiryDate { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CustomerRepId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string RegistrationNo { get; set; }
        public string VATNo { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string NormalizedName { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<decimal> OpeningDebitBalance { get; set; }
        public Nullable<decimal> OpeningCreditBalance { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerRep CustomerRep { get; set; }
        public virtual Department Department { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyNotification> PropertyNotifications { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContract> PropertyContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRenterImage> PropertyRenterImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContractTermination> PropertyContractTerminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitAndCreditNotification> DebitAndCreditNotifications { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
    }
}
