//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyBatches = new HashSet<PropertyBatch>();
            this.PropertyContracts = new HashSet<PropertyContract>();
            this.PropertyDetails = new HashSet<PropertyDetail>();
            this.PropertyContractTerminations = new HashSet<PropertyContractTermination>();
            this.PropertyPaymentHistory = new HashSet<PropertyPaymentHistory>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public string PropertySequence { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CollectorId { get; set; }
        public Nullable<int> FixedAssetId { get; set; }
        public Nullable<decimal> TotalDepreciation { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string NeighborhoodName { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> ChronologicalAge { get; set; }
        public Nullable<decimal> CurrentPropertyPrice { get; set; }
        public Nullable<decimal> LastRentalValue { get; set; }
        public Nullable<int> MaintenanceTypeId { get; set; }
        public Nullable<int> PropertyStatusId { get; set; }
        public Nullable<int> EntriesNo { get; set; }
        public Nullable<int> FloorsNo { get; set; }
        public Nullable<int> CommercialUnitsNo { get; set; }
        public Nullable<int> ParkingsNo { get; set; }
        public Nullable<int> FrontispieceId { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public Nullable<int> HousingUnitsNo { get; set; }
        public Nullable<double> CommissionPercentage { get; set; }
        public Nullable<decimal> DeductedAmount { get; set; }
        public string SiteDescription { get; set; }
        public Nullable<int> PropertyOwnerId { get; set; }
        public string Agent { get; set; }
        public string AgencyNo { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string Conditions { get; set; }
        public Nullable<int> YearsNo { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public Nullable<decimal> ContractValueWithoutTax { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<decimal> AnnualIncrease { get; set; }
        public Nullable<bool> IsCommission { get; set; }
        public Nullable<int> NumberOfBatches { get; set; }
        public Nullable<System.DateTime> FirstBatchDate { get; set; }
        public Nullable<int> PeriodBetweenBatchesNum { get; set; }
        public Nullable<int> PeriodBetweenBatchesTypeId { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual FixedAsset FixedAsset { get; set; }
        public virtual PropertyOwner PropertyOwner { get; set; }
        public virtual PropertyStatu PropertyStatu { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyBatch> PropertyBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContract> PropertyContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyDetail> PropertyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContractTermination> PropertyContractTerminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyPaymentHistory> PropertyPaymentHistory { get; set; }
    }
}
