//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertySummaryNew
    {
        public int Id { get; set; }
        public string Building { get; set; }
        public Nullable<decimal> ContractValueWithoutTax { get; set; }
        public Nullable<decimal> RentValue { get; set; }
        public Nullable<int> PropertyStatusId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> RoomsNo { get; set; }
        public Nullable<int> TotalApartments { get; set; }
        public Nullable<int> FreeApartments { get; set; }
        public Nullable<decimal> TotalRent { get; set; }
        public Nullable<int> YearsNo { get; set; }
    }
}
