//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyContractFixLog
    {
        public int LogId { get; set; }
        public System.Guid RunId { get; set; }
        public string TableName { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public string FieldName { get; set; }
        public Nullable<decimal> OldValue { get; set; }
        public Nullable<decimal> NewValue { get; set; }
        public string Reason { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string ChangedBy { get; set; }
        public bool IsReverted { get; set; }
        public Nullable<System.DateTime> RevertedAt { get; set; }
    }
}
