//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceActualPayment
    {
        public int Id { get; set; }
        public Nullable<int> PurchaseInvoiceId { get; set; }
        public Nullable<System.DateTime> PurchaseInvoiceDate { get; set; }
        public string PurchaseInvoiceDocNumber { get; set; }
        public Nullable<int> CashIssueVoucherId { get; set; }
        public Nullable<int> ChequeIssueId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> NetAmountRemain { get; set; }
    
        public virtual CashIssueVoucher CashIssueVoucher { get; set; }
        public virtual ChequeIssue ChequeIssue { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
    }
}
