//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomBooking()
        {
            this.RoomLeavePermissions = new HashSet<RoomLeavePermission>();
            this.RoomBookingDays = new HashSet<RoomBookingDay>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> BookingStartDate { get; set; }
        public Nullable<System.DateTime> BookingEndDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAfterDiscount { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CashBoxId { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Remain { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<int> BookingStatusId { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> RequiredAmount { get; set; }
        public Nullable<decimal> RoomPrice { get; set; }
        public Nullable<int> NightsNumber { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<decimal> TotalAfterTaxes { get; set; }
        public string OnlinePaymentId { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public Nullable<int> BookingEmployeeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual Room Room { get; set; }
        public virtual Building Building { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomLeavePermission> RoomLeavePermissions { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBookingDay> RoomBookingDays { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
