//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceActualPayment
    {
        public int Id { get; set; }
        public Nullable<int> SalesInvoiceId { get; set; }
        public Nullable<System.DateTime> SalesInvoiceDate { get; set; }
        public string SalesInvoiceDocNumber { get; set; }
        public Nullable<int> CashReceiptVoucherId { get; set; }
        public Nullable<int> ChequeReceiptId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> NetAmountRemain { get; set; }
    
        public virtual ChequeReceipt ChequeReceipt { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual CashReceiptVoucher CashReceiptVoucher { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
