//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesQuotationDetail
    {
        public int Id { get; set; }
        public Nullable<int> MainDocId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> ItemPriceId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ItemUnitId { get; set; }
        public Nullable<double> UnitEquivalent { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> CurrencyEquivalent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<double> DiscountPerc { get; set; }
        public Nullable<int> WareHouseId { get; set; }
        public Nullable<double> WarrantyPeriod { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> PatchId { get; set; }
        public Nullable<int> SystemPageId { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<double> RemainQty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> ItemDirectExpenses { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Area { get; set; }
        public string ChassisNo { get; set; }
        public string EngineNo { get; set; }
        public Nullable<int> ManufacturingYear { get; set; }
        public string PlateNo { get; set; }
        public string VehicleNotes { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ItemPrice ItemPrice { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Item Item { get; set; }
        public virtual SalesQuotation SalesQuotation { get; set; }
        public virtual SystemPage SystemPage { get; set; }
        public virtual Patch Patch { get; set; }
        public virtual CarColor CarColor { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual CarType CarType { get; set; }
    }
}
