//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrdersSalesInvoice
    {
        public int Id { get; set; }
        public int SalesInvoiceId { get; set; }
        public int SalesOrderId { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
