//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surgery()
        {
            this.SurgeryAnalysis = new HashSet<SurgeryAnalysi>();
            this.SurgeryAnalysisImages = new HashSet<SurgeryAnalysisImage>();
            this.SurgeryImages = new HashSet<SurgeryImage>();
            this.SurgeryMedicines = new HashSet<SurgeryMedicine>();
            this.SurgeryRays = new HashSet<SurgeryRay>();
            this.SurgeryRayImages = new HashSet<SurgeryRayImage>();
        }
    
        public int Id { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> MedicalSpecialtyId { get; set; }
        public Nullable<int> AssistantDoctorId { get; set; }
        public Nullable<int> AssistantNurseId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Image { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> DoctorPrice { get; set; }
        public Nullable<decimal> AssistantPrice { get; set; }
        public Nullable<decimal> NursePrice { get; set; }
        public string Video { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<int> TurnNo { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<int> InsuranceCompanyId { get; set; }
        public Nullable<decimal> InsuranceRatio { get; set; }
        public Nullable<decimal> PatientRatio { get; set; }
        public string OrganName { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ERPUser ERPUser { get; set; }
        public virtual MedicalSpecialty MedicalSpecialty { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryAnalysi> SurgeryAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryAnalysisImage> SurgeryAnalysisImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryImage> SurgeryImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryMedicine> SurgeryMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryRay> SurgeryRays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgeryRayImage> SurgeryRayImages { get; set; }
    }
}
