//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncedDepartment
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public bool IsSynced { get; set; }
        public int ChangeId { get; set; }
    
        public virtual DBChange DBChange { get; set; }
    }
}
