//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechanicianService
    {
        public int Id { get; set; }
        public Nullable<int> TechanicianId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Notes { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Choosen { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual ServicesCategory ServicesCategory { get; set; }
        public virtual Techanician Techanician { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
